### ISSUE TITLE
META: Better instance homepage

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#430]
- [x] explain what the site is (#740)
- [x] move 'sending a message' to a separate page.
- [x] include X recent messages + X recent replies rather than all messages.

**Comment by schlos** [comment]
+1

**Comment by martinszy** [comment]
I would like to have a count of all the messages for an instance.
Also, the "recent" counts, should include all messages processed, even in they were deleted.

**Comment by tmtmtmtm** [comment]
@martinszy — you're asking for these for the *public* home page of an instance, or for the front of the admin section?

**Comment by tmtmtmtm** [comment]
#987 has given us enough of an About page to close this.
