### ISSUE TITLE
META: 'Message' page

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#447]
- [x] Recipient name should be a link (#440)
- [x] Sender name should be a link (#795)
- [x] Should include date information for messages (#438)
- [x] Should explicitly note "No responses yet" (where applicable) (#746)

**Comment by tmtmtmtm** [comment]
All done!
