### ISSUE TITLE
META: 'Message Composer' page

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#453]
- [x] Should be on a page of its own
- [x] Don't show the "Trailing * means that we don't have how to contact the person" text [#677]
- [x] Don't display the form at all if there are no contacts [#401] 
- [x] Don't display the form at all if set to only accept messages via the API [#716]
- [x] Remove the public/private toggle [#436]
- [ ] Explain what the process is going to be (e.g. that they'll need to confirm by email)

**Comment by tmtmtmtm** [comment]
I'm happy with this page!
