### ISSUE TITLE
Source Manager: Problems with linking a new PopIt

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#816]
I added the bottom URL:

![fetching data 2015-04-09 at 13 55 51](https://cloud.githubusercontent.com/assets/57483/7067304/146bfc2e-dec2-11e4-9816-b8e2e10e6179.png)

- [x] It shouldn't let me add a URL that's not to an API, unless it's going to handle that
    - [x] Though ideally it should Do The Right Thing, rather than complaining! (#847)
        - [x] If it *does* convert it to the API URL, we should ensure that it does the check for duplication *after* that conversion, not before. (#724)
- [ ] "inprogress" looks an internal status leaking out, rather than a textual representation of it (is that what #622 is about?)
- [x] We have two separate flash messages (sometimes three: #967)
- [x] The text of the flash (if needed at all) should be better. Maybe something more like "{name of popit} added"?
- [x] As this isn't a valid API URL it will fail, but not tell me why (#728)

**Comment by lfalvarez** [comment]
In the PR #812 the problem " If it does convert it to the API URL, we should ensure that it does the check for duplication after that conversion, not before." is being taken care of. I'm sorry to have fixed that there but I was so close to it =/

**Comment by tmtmtmtm** [comment]
@lfalvarez No, that's good — I was just making the note here so that we could make sure we do the various things here in the right order. :)

**Comment by tmtmtmtm** [comment]
I'm not quite sure how it let me add https://riigikogu.popit.mysociety.org/ without auto-completing that to the API URL, as this was fixed in #510...

**Comment by tmtmtmtm** [comment]
Only thing left is #622, so closing this one.
