### ISSUE TITLE
Message Manager is still confusing

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#827]
![message manager 2015-04-09 at 22 16 02](https://cloud.githubusercontent.com/assets/57483/7077139/6a0afbb4-df06-11e4-8391-ac942f5b8c4a.png)

We have four rows that show various binary options for a message, with an unrelated row in the middle that tells you how many responses it has had. 

Two of them are purely informational as to the status (though at least one of those _should_ let you change it #782); two of them _do_ let you change it — but in different ways. 

Two of them (at opposite ends! #720) refer to to the same status (public/private) — one just telling you what it is, the other providing a somewhat confusing icon that lets you toggle the status (though it probably shouldn't #779.)

"Moderate" (as a text button this time, and misleading text at that, see #583) only lets you set to "Yes" — there's no way to reject a message from here — and once clicked, turns into a purely informational tick/cross combo. Furthermore, if messages exist from before Moderation was even turned on in the instance (as here), clicking "Moderate" on those earlier messages will simply give an error (#704). The "Moderate" button also displays for messages that haven't been confirmed yet — clicking it gives a 'The message needs to be confirmated first" error.
 
Some suggestions (though this might just need an entire rethink):
- [x] Separate the "number of replies" from the other columns (at least move it to the leftmost column, but preferably do something entirely better)
- [x] Don't show the "Moderate" button for messages it doesn't apply to (#704)
- [x] Have separate "Approve / Reject" actions for messages needing moderation (#583)
- [x] Group the two "Public?" columns together (#720)
- [ ] Add a confirmation step to making a message public that is currently private (#779) 
- [x] Shouldn't say "in your WriteIt" [#530] — probably best to just drop this entirely here

**Comment by tmtmtmtm** [comment]
See also #858

**Comment by tmtmtmtm** [comment]
Everything here is either done, or ticketed separately, so closing this one.
